language: php

php:
  - 7.0

install:
  - composer install

script: skip

after_success:
  #- "find vendor -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/{} \\;"
  - "find api -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/{} \\;"
  - "find app -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/{} \\;"
  - "curl -T index.php --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/"

env:
  global:
    - secure: 4GXoO5aVojXHgsPxSDKAyztLpK7+TlU/wBacRs+7P2ocKZQXQ6wMR8cCp/fN2dSpNYwTVcK+yQG1CvU4jFdln7lYi7HFXs9M41xJV6kQu7LAYBYdGaDwNYxnSsNPNQNt8tNDpFb7E/tP2WDcIqXaHFfi4YIwo0GMVJlCQMyPtUeZagN8+YCcAiegtH8NEzGzoUcEdkZteXSFYu3fTAqYj0FZreVZ8FeKXbhY7cU0QtVv3SiDhyPdebY3AKHH5MCmhZTrnwGRkn6BwK3SkJHUdAxzOWsqy1TPain3G62DcEKOpMqywy7Z5gFv6IchDi4tfwVpPc17mtrg3XGufczDscifa3hsNOBzz9tVaY2wzUgT/npfAhxnN4xq0JINabSarK0E4+yfii4EbMGQPgBL+5RktimEAGbJjjalYmrf1FIMxQMPlzk1jXzv940PreZjuwYNp08T0kkmDnSsMiYSxmKzQcwvXphfFXqX7NLATUAo7iTXZprH+K60juw7rUZWWXofqknp3lYdHPaK/MhEc/sQudbMrI7Q8qTfjSXpj6JqfTQ0NYJ2AxNth0xHoRmpe6b0p86LxBmHIfS5j5G1v0BjG4+FIUYyU2Rv1te/D/mQC1lsSR+1adzVmZ81uQZsuNuKIkrlEPlGnxR91FCekSpo9C36jIVaflRx3w6uDjg=
    - secure: nQD+nqK7RsVHXj1abL57NwfLi3tC0qEvXOWo6v/Nt38vG+J2mj6vBtv/ppnmcGOHseX0sdlEfxuZGYrlzU8mypUo/w7xHWx+GWkkioC8birdDGCdof1r/HTSoiZpJgeNHszXLhI00lEA/eQQbm8mt30YPErEb27Auj3YjBxPLG/mFsMGdpWw1lX0SjV2qKXVZySHKD2Lvk/+EI+wVA3Kmqjrkx+I+fkg7SbPd+JyElfRf4ppsON+nl4UKhicrWI9srbH45cm0dvpuURgx7F2JG4dxIKjXdAOCZU5E1MdDV0wcRCWD+kZI7GL7VOb8kAGmLrtNvw5RS5gbTiPb2tYgxkQrKrsbFRBbRrqfZ8hmDRTk2rxtOALyN/gkqOZBWGAgZeh1EJqUswNZyaz8LZ3SUhmghi3mB4RKkymI+3P6ZAJwQ3N/iHWIccBqQTNx6yqI4he7UY1xNs1Nw+iZInGiKM/Z4wWqXqWJV8Djfe22ZFxGwpxwJ6AoQuv/GHSUv9krQcpOcEaLe7ndaTXuLXi2GeJxzMp6Jwt0w9+5uPnAqiq0039QPkst8cZutJK0cK36a1o4oV0rwaZeZ+1aJi7As5zyVy32ewG0nDJGCn3DUSFmLhhfkdzF6NmFXL2D5fVsgbCRnl9IWX8NyDiqUd9Xew+qtHUmJJANABk1Wr6nrM=
